apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: counter
spec:
  broker: broker
  filter: {}
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: counter
